on:
  workflow_dispatch:
  schedule:
   - cron: "0 * * * *"

env:
  GITHUB_TOKEN: ${{ secrets.FILE_SYNC_PAT }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.FILE_SYNC_PAT }}

      - uses: champ-oss/file-sync@v1.0.52-767cdaa
        with:
          token: ${{ secrets.FILE_SYNC_PAT }}
          repo: reeves122/micro-airlines-api-go
          files: |
            .gitignore
            LICENSE