on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v3
        with:
          args: "--out-${NO_FUTURE}format colored-line-number"
