on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - uses: golangci/golangci-lint-action@v3.3.1
        with:
          args: "--out-${NO_FUTURE}format colored-line-number"
