on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Unit Tests
      run: go test -v ./...

    - name: Generate Coverage Report
      run: |
        go test -json -coverprofile=cover.out ./... > result.json
        go tool cover -func cover.out
